# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [5]:
sinasc_raw = pd.read_csv("C:\\Users\\alcid\\GitHub\\Portfolio\\EBAC\\Dados\\SINASC_RO_2019.csv")
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [80]:
sinasc_raw.groupby('munResNome')[['IDADEMAE','IDADEPAI']].mean().sort_values(by='IDADEPAI', ascending=False)

                            IDADEMAE   IDADEPAI
munResNome
Itapuã do Oeste            26.064220  42.500000
Cacaulândia                25.546667  36.333333
Pimenteiras do Oeste       25.075000  35.600000
Monte Negro                25.648241  34.678571
Colorado do Oeste          27.602804  34.354839
Cabixi                     26.037500  34.333333
Vilhena                    26.433962  34.152941
Vale do Anari              26.096774  34.000000
Ministro Andreazza         27.904762  33.849315
São Miguel do Guaporé      25.926346  32.666667
Parecis                    26.454545  32.473684
Corumbiara                 24.716535  32.470588
Ariquemes                  25.607866  32.466667
Porto Velho                26.312670  32.352679
Jaru                       25.982974  32.197183
Mirante da Serra           26.304878  32.154762
Primavera de Rondônia      27.023256  31.888889
Nova Mamoré                25.326389  31.692308
Cerejeiras                 27.240506  31.652778
São Francisco do Guaporé   25.660066  31.638889
Novo Horizonte do Oeste    26.938776  31.588235
Teixeirópolis              26.031250  31.500000
Cujubim                    24.482927  31.400000
São Felipe D'Oeste         26.481481  31.395833
Nova União                 26.894231  31.371429
Machadinho D'Oeste         25.480000  31.326923
Ouro Preto do Oeste        26.375594  31.233244
Espigão D'Oeste            26.093333  31.198113
Ji-Paraná                  26.361137  31.132239
Urupá                      26.688235  31.008929
Cacoal                     26.890102  30.931854
Buritis                    25.559177  30.812500
Alvorada D'Oeste           25.770732  30.757282
Santa Luzia D'Oeste        26.121212  30.703297
Costa Marques              24.412017  30.613636
Nova Brasilândia D'Oeste   26.222222  30.520833
Seringueiras               24.910714  30.500000
Campo Novo de Rondônia     24.825301  30.500000
Guajará-Mirim              25.462228  30.470588
Castanheiras               27.281250  30.392857
Rolim de Moura             26.600863  30.360479
Presidente Médici          25.796053  30.150754
Theobroma                  25.536082  30.083333
Vale do Paraíso            25.679012  29.976744
Candeias do Jamari         25.243323  29.894737
Pimenta Bueno              25.199675  29.745174
Chupinguaia                25.333333  29.629630
Alta Floresta D'Oeste      25.991826  29.548701
Governador Jorge Teixeira  24.401786  29.222222
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Rio Crespo                 26.660000  28.000000
Município ignorado - RO    24.000000  22.000000

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [34]:
sinasc_raw.loc[sinasc_raw['DTNASC'].str.contains('10-27')].groupby(['SEXO','ESCMAE'])[['PESO']].mean()

                                  PESO
SEXO      ESCMAE
Feminino  12 anos ou mais  2905.000000
          4 a 7 anos       2891.000000
          8 a 11 anos      3220.357143
Masculino 12 anos ou mais  3162.500000
          4 a 7 anos       2909.888889
          8 a 11 anos      3286.058824

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [70]:
cidade = sinasc_raw.groupby('munResNome')[['ORIGEM']].count().sort_values(ascending=True, by='ORIGEM')
print(f'Cidade que nasceu menos pessoas foi {cidade.index[0]}, com um total de {cidade.values[0,0]}')

print(f'\nComo esse dado aparenta mais ser algum tipo de ERRO, o município levado em consideração será o segundo, no caso {cidade.index[1]}')
print(f'Que apresentou um total de {cidade.values[1,0]} nascimentos.\n')


sinasc_raw.loc[sinasc_raw['munResNome'] == cidade.index[1]].groupby(['munResNome'])[['IDADEPAI','IDADEMAE']].agg(['mean','max','min']).T

Cidade que nasceu menos pessoas foi Município ignorado - RO, com um total de 1

Como esse dado aparenta mais ser algum tipo de ERRO, o município levado em consideração será o segundo, no caso Castanheiras
Que apresentou um total de 32 nascimentos.

munResNome     Castanheiras
IDADEPAI mean     30.392857
         max      43.000000
         min      17.000000
IDADEMAE mean     27.281250
         max      39.000000
         min      17.000000

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [76]:
cidade = sinasc_raw.groupby('munResNome')[['ORIGEM']].count().sort_values(ascending=False, by='ORIGEM')
print(f'Cidade que nasceu menos pessoas foi {cidade.index[0]}, com um total de {cidade.values[0,0]}')


display(sinasc_raw.loc[sinasc_raw['munResNome'] == cidade.index[0]].groupby(['munResNome'])[['QTDFILVIVO']].agg(['mean','max','min']).T)
display(sinasc_raw.loc[sinasc_raw['munResNome'] == cidade.index[0]].groupby(['munResNome'])[['IDADEPAI']].agg(['mean','max','min']).T)

Cidade que nasceu menos pessoas foi Porto Velho, com um total de 8437

munResNome       Porto Velho
QTDFILVIVO mean     1.167236
           max     12.000000
           min      0.000000

munResNome     Porto Velho
IDADEPAI mean    32.352679
         max     65.000000
         min     16.000000

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

<h3> Insights </h3>

Comparando os municípios, alguns insights são, no mínimo, interessantes.
<li> O município de Ministro Andreazza apresenta a maior média de idade das mães, em torno de, aproximadamente, 28, enquanto o município de Governador Jorge Teixeira apresenta uma faixa de, aproximadamente, 24. </li>
<li> Em relação a idade dos pais, a cidade de Itapuã do Oeste apresentou uma média de 42 anos de idade, enquanto Rio crespo apresentou uma média de 28 anos.</li>
<li> Fica claro que a tendência é existir uma diferença de idade entre Pai e Mãe das crianças.
<li> Analisando agora o peso dos bebês em relação a escolaridade da mãe, vemos que há diferença dos pesos em relação ao sexo, já comparando a escolaridade das mães, seria necessário uma análise estatística para averiguar se essa diferença é significativa ou não.</li>
<li> Comparando as idades tanto de pai e mãe, em relação a cidade com menos bebês, vemos que a diferença de idades identificada anteriormente permanece presente aqui. </li>
<li> Por último, vemos que na cidade de porto velho, sendo a cidade com mais bebês nascidos, a média de filhos vivos é acima de um, levando a entender que a tendência de nascimento foram já de mulheres previamente mães antes do nascimento do registro.